# Generated by Django 3.1.1 on 2020-09-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('converter', models.CharField(choices=[('szt', 'Sztuki'), ('kg', 'Kilogram'), ('dag', 'Dekagram'), ('g', 'Gram'), ('l', 'Litr'), ('ml', 'Mililitr'), ('szczypta', 'Szczypta')], default='szt', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('graphics', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('inne', 'Inne'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial'), ('mięso', 'Mieso'), ('ryby', 'Ryby'), ('przyprawy', 'Przyprawy')], default='inne', max_length=20)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preparation', models.TextField()),
                ('time', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('ingredients', models.ManyToManyField(to='backendApp.Ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.products'),
        ),
    ]
