# Generated by Django 3.0b1 on 2020-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='popularnosc',
            field=models.IntegerField(default=0),
        ),
    ]
