# Generated by Django 3.1.1 on 2020-10-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id_graphic',
            new_name='graphic',
        ),
    ]
