# Generated by Django 3.1.1 on 2020-10-20 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20201015_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='graphic',
        ),
        migrations.AddField(
            model_name='products',
            name='graphic_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Graphics',
        ),
    ]
