# Generated by Django 3.1.1 on 2020-10-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_auto_20201020_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='graphic_id',
        ),
        migrations.AddField(
            model_name='products',
            name='graphic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
