# Generated by Django 3.1.1 on 2020-10-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_auto_20201022_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='graphic',
            new_name='graphics',
        ),
    ]
