# Generated by Django 3.1.1 on 2020-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_auto_20201022_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
