# Generated by Django 3.1.1 on 2020-10-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_recipes_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
