# Generated by Django 3.0b1 on 2020-08-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('grafika', models.FileField(blank=True, null=True, upload_to='')),
                ('kategoria', models.CharField(choices=[('inne', 'Inne'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial'), ('mięso', 'Mieso'), ('ryby', 'Ryby'), ('przyprawy', 'Przyprawy')], default='inne', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skladniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.FloatField(null=True)),
                ('przelicznik', models.CharField(choices=[('szt', 'Sztuki'), ('kg', 'Kilogram'), ('dag', 'Dekagram'), ('g', 'Gram'), ('l', 'Litr'), ('ml', 'Mililitr'), ('szczypta', 'Szczypta')], default='szt', max_length=20)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.Produkty')),
            ],
        ),
        migrations.CreateModel(
            name='Przepisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('przygotowanie', models.TextField()),
                ('czas', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('skladniki', models.ManyToManyField(to='backendApp.Skladniki')),
            ],
        ),
    ]
