# Generated by Django 3.0.9 on 2020-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('przelicznik', models.CharField(choices=[('kg', 'Kilogram'), ('dag', 'Dekagram'), ('g', 'Gram'), ('szt', 'Sztuki'), ('l', 'Litr'), ('ml', 'Mililitr')], default='kg', max_length=20)),
                ('grafika', models.FileField(blank=True, null=True, upload_to='')),
                ('kategoria', models.CharField(choices=[('pozostałe', 'Pozostale'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial')], default='pozostałe', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Przepisy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('przygotowanie', models.TextField()),
                ('czas', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('skladniki', models.ManyToManyField(to='backendApp.Produkty')),
            ],
        ),
    ]
