# Generated by Django 3.0.9 on 2020-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('owoce', 'owoce'), ('warzywa', 'warzywa')], default='owoce', max_length=20),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='przelicznik',
            field=models.CharField(choices=[('kilogram', 'kg'), ('gram', 'g')], default='kilogram', max_length=20),
        ),
    ]
