# Generated by Django 3.0.9 on 2020-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20200803_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('pozostałe', 'Pozostale'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial')], default='pozostałe', max_length=20),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='przelicznik',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('dag', 'Dekagram'), ('g', 'Gram'), ('szt', 'Sztuki'), ('l', 'Litr'), ('ml', 'Mililitr')], default='kg', max_length=20),
        ),
    ]
