# Generated by Django 3.0.9 on 2020-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_auto_20200807_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('owoce', 'owoce'), ('warzywa', 'warzywa')], default='owoce', max_length=20),
        ),
    ]
