# Generated by Django 3.0.9 on 2020-08-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_auto_20200807_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('pozostałe', 'Pozostale'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial')], default='pozostałe', max_length=20),
        ),
    ]
