# Generated by Django 3.0.9 on 2020-08-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_auto_20200807_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('inne', 'Inne'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial'), ('mięso', 'Mieso'), ('ryby', 'Ryby')], default='inne', max_length=20),
        ),
    ]
