# Generated by Django 3.0.9 on 2020-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_auto_20200809_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='kategoria',
            field=models.CharField(choices=[('inne', 'Inne'), ('owoce', 'Owoce'), ('warzywa', 'Warzywa'), ('zboża', 'Zboza'), ('nabiał', 'Nabial'), ('mięso', 'Mieso'), ('ryby', 'Ryby'), ('przyprawy', 'Przyprawy')], default='inne', max_length=20),
        ),
    ]
