# Generated by Django 3.0.9 on 2020-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_auto_20200811_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='przelicznik',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('dag', 'Dekagram'), ('g', 'Gram'), ('szt', 'Sztuki'), ('l', 'Litr'), ('ml', 'Mililitr'), ('szczypta', 'Szczypta')], default='kg', max_length=20),
        ),
    ]
